// Mocks generated by Mockito 5.1.0 from annotations
// in flupteka_app/test/aid_kit_page_test.dart.
// Do not manually edit this file.

import 'package:flupteka_app/aid-kit/aid_kit_page.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Storage].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorage extends _i1.Mock implements _i2.Storage {
  MockStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> loadNames() =>
      (super.noSuchMethod(Invocation.method(#loadNames, []),
          returnValue: <String>[]) as List<String>);
  @override
  List<int> loadQuantities() =>
      (super.noSuchMethod(Invocation.method(#loadQuantities, []),
          returnValue: <int>[]) as List<int>);
  @override
  void storeNames(List<String>? names) =>
      super.noSuchMethod(Invocation.method(#storeNames, [names]),
          returnValueForMissingStub: null);
  @override
  void storeQuantities(List<int>? names) =>
      super.noSuchMethod(Invocation.method(#storeQuantities, [names]),
          returnValueForMissingStub: null);
}
