include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_single_quotes: error
    missing_required_param: warning

linter:
  rules:
    prefer_single_quotes: true
    annotate_overrides: true
    missing_required_param: true

